// Generated by CoffeeScript 1.8.0
(function() {
  var T, attributify, createTag, createTagFunction, formatAttributes, getRawContent, isFunction, tag, tags, _i, _len,
    __slice = [].slice;

  tags = ['a', 'abbr', 'acronym', 'address', 'applet', 'area', 'article', 'aside', 'audio', 'b', 'base', 'basefont', 'bdo', 'big', 'blockquote', 'body', 'br', 'button', 'canvas', 'caption', 'center', 'cite', 'code', 'col', 'colgroup', 'command', 'datalist', 'dd', 'del', 'details', 'dfn', 'dir', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'figcaption', 'figure', 'font', 'footer', 'form', 'frame', 'frameset', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'header', 'hgroup', 'hr', 'html', 'i', 'iframe', 'img', 'input', 'ins', 'keygen', 'kbd', 'label', 'legend', 'li', 'link', 'map', 'mark', 'menu', 'meta', 'meter', 'nav', 'noframes', 'noscript', 'object', 'ol', 'optgroup', 'option', 'output', 'p', 'param', 'pre', 'progress', 'q', 'rp', 'rt', 'ruby', 's', 'samp', 'script', 'section', 'select', 'small', 'source', 'span', 'strike', 'strong', 'style', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'title', 'tr', 'tt', 'u', 'ul', 'var', 'video', 'wbr', 'xmp'];

  isFunction = function(object) {
    var getType;
    getType = {};
    return object && getType.toString.call(object) === '[object Function]';
  };

  formatAttributes = function(attributes) {
    var formattedAttributes, key, value;
    if (attributes == null) {
      return "";
    }
    formattedAttributes = [];
    for (key in attributes) {
      value = attributes[key];
      formattedAttributes.push("" + key + "='" + value + "'");
    }
    return ' ' + formattedAttributes.join(' ');
  };

  attributify = function(selector) {
    var attributes, classes, ids, _ref, _ref1;
    classes = (_ref = selector.match(/\.\w+/g)) != null ? _ref.map(function(name) {
      return name.slice(1);
    }) : void 0;
    ids = (_ref1 = selector.match(/#\w+/g)) != null ? _ref1.map(function(name) {
      return name.slice(1);
    }) : void 0;
    attributes = {};
    if (ids != null) {
      attributes.id = ids.join(' ');
    }
    if (classes != null) {
      attributes["class"] = classes.join(' ');
    }
    return attributes;
  };

  getRawContent = function(content) {
    if (isFunction(content)) {
      content = content();
    }
    if (Array.isArray(content)) {
      content = content.join('');
    }
    return content;
  };

  createTag = function(tagName) {
    return function(content, attributes, selector) {
      var formattedAttributes, key, value, _ref;
      if (selector == null) {
        selector = '';
      }
      content = getRawContent(content);
      if (typeof attributes === 'string') {
        attributes = attributify(attributes);
      }
      _ref = attributify(selector);
      for (key in _ref) {
        value = _ref[key];
        attributes[key] = value;
      }
      formattedAttributes = formatAttributes(attributes);
      return "<" + tagName + formattedAttributes + ">" + content + "</" + tagName + ">";
    };
  };

  createTagFunction = function(tagName, bindTarget) {
    return bindTarget[tagName] = function() {
      var args, reversedArgs;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      reversedArgs = args.reverse();
      return createTag(tagName).apply(null, reversedArgs);
    };
  };

  T = {};

  for (_i = 0, _len = tags.length; _i < _len; _i++) {
    tag = tags[_i];
    createTagFunction(tag, T);
  }

  if (typeof window !== "undefined" && window !== null) {
    window.T = T;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = T;
  }

}).call(this);
